#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate sass/moe_w3_mm.sass — M<=4 GEMM over 3-bit tensor-sym planes.

W3 = the codebook-WIDTH sibling of moe_w2_mm (SAPID P3b):
LUT 4 -> 8 entries, plane stride 2 -> 3 bits/code. SAME QMMA core, SAME
block-32 UE8M0 scale plumbing, SAME desc/epilogue.

C[M,N] (bf16) = A(fp8 e4m3, [M,K]) @ W(3-bit codes, 8-level e4m3 LUT
{-6,-3,-1.5,-0.5,0.5,1.5,3,6}, block-32 UE8M0 scales) ^T, with per-token-
group-128 f32 activation scales folded per kb128 (skinny fold lineage).

Plane layout (pack_w3_plane in the check harness): per (nb, k64) block =
384 bytes: [256B low plane -- BYTE-IDENTICAL layout to the W2 fragment-major
plane over (code & 3)] ++ [128B hi plane: one u32 per lane; bit (byte*4 +
kfrag) = code>>2 of the same code the low byte holds at that position].
Lane loads LDG.E.64 (8B low, as W2) + LDG.E (4B hi) per k64.

Decode per byte-group: the verbatim W2 2-bit nibble spread (4x LOP3 + 3x
IMAD) builds selector bits [4i..4i+1]; the hi merge (1 SHF/MOV + 4x LOP3 +
4x IMAD) ORs code-bit2 into selector bit [4i+2]; one PRMT over the 8-byte
pool {R27, R13} (same two-register pool structure as gen_moe_w4's mag LUT)
yields 4 e4m3 bytes. Everything downstream of the decoded B regs (QMMA.SF,
sfb bytes, kb128 fold, smem reduce, bf16 store) is the W2 kernel verbatim.

Geometry: grid.x = N/16, grid.y = num (expert, token-group) pairs;
NWARP=8 split-K for K>=1024; desc = 6 x u64 per pair {a, as, b, bs, c,
m_rows}. K/N compile-time per cubin (K via argv, N free).

bpw: 3 (codes) + 8/32 (UE8M0 block-32) = 3.25 exactly.

VARIANTS (prefill extension; branches ported verbatim from
gen_moe_w2.py @ 591250b — the hi-plane merge is orthogonal to both, it
lives entirely in the byte-group decode):
  MOEW3_MC=4    fold the QMMA c2/c3 quadrants too -> rows 8..15 in the
                SAME decode pass = the FULL m16 tile (prefill primitive).
  MOEW3_AFRAG=1 A pre-packed FRAGMENT-MAJOR: one LDG.E.128 per k32
                replaces 4 strided LDG.E (requires MC=4). Occupancy-
                neutral (regcount stays 64 = 4 CTA/SM).
Default (MC=1, AFRAG=0) emission is BIT-IDENTICAL to the sealed SDR
generator d24986bf (K=4096: sass 3f87f18e / cubin 56a4b9de).
"""

import os
import sys

K = int(sys.argv[2]) if len(sys.argv) > 2 else 4096


def _nwarp(k):
    nb = k // 128
    cap = 8 if k >= 1024 else 4
    for n in range(min(cap, nb), 0, -1):
        if nb % n == 0:
            return n
    return 1


NWARP = int(os.environ.get("MOEW3_NWARP", "0")) or _nwarp(K)
MC = int(os.environ.get("MOEW3_MC", "1"))      # m-chunks per pair-entry
# MC=1: c0/c1 only (rows 0..7);  MC=4: fold the QMMA's c2/c3 quadrants too
# -> rows 8..15 in the SAME decode pass = the FULL m16 tile. (MC=2 not
# ported: the W2 perf table used mc4 + mc4afrag only.)
assert MC in (1, 4)
AFRAG = int(os.environ.get("MOEW3_AFRAG", "0"))
assert AFRAG in (0, 1)
if AFRAG:
    assert MC == 4, "AFRAG requires MC=4 (full m16 fragment)"
KSLICE = K // NWARP
assert KSLICE % 128 == 0
NTHR = NWARP * 32
SMEM = NWARP * 1024 + (2048 if NTHR > 256 else 0)
ACC0, ACC1 = 48, 52

OUT = []


def L(s=""):
    OUT.append(s)


L("// moe_w3_mm — M<=4 GEMM over 3-bit tensor-sym planes (GENERATED by")
L("// gen_moe_w3.py — edit the generator, not this file).")
L("// 2-bit low plane (W2-layout) + 1-bit hi plane -> 3-bit PRMT selector;")
L("// 8-entry e4m3 LUT {-6,-3,-1.5,-0.5,.5,1.5,3,6} in pool {R27,R13};")
L("// block-32 UE8M0 via QMMA.SF sfb; A-side f32 scales folded per kb128;")
L("// per-(expert,token-group) desc table indexed by CTAID.Y. W2 lineage.")
L(".entry moe_w3_mm")
L("    .reg R0-R95")
L("    .param u64 d_desc")        # [pairs][6] u64 table
L("    .param u32 ldb")           # K (bytes per A row)
L("    .param u32 n_k64")
L("    .param u32 ldc")           # N*2
L("    .param u32 n_kb128")
L(f"    .shared .align 16 smem[{SMEM}]")
L()
L("    // ---- prologue ----")
L("    S2R R80, SR_TID.X ;")
L("    LDCU.64 UR4, c[0x0][0x358] ;")
L("    UMOV UR6, 0x0 ;")
L("    S2R R81, SR_CTAID.X ;                    // n-block (16 rows)")
L("    S2R R92, SR_CTAID.Y ;                    // (expert, token-group) pair")
L("    LDC R82, c[0x0][0x388] ;                 // ldb = K")
L("    LDC R84, c[0x0][0x394] ;                 // n_kb128")
L("    SHF.R.U32.HI R85, RZ, 0x5, R80 ;         // wid")
L("    LOP3.LUT R86, R80, 0x1f, RZ, 0xc0, !PT ; // lane")
L("    SHF.R.U32.HI R87, RZ, 0x2, R86 ;         // g")
L("    LOP3.LUT R88, R86, 0x3, RZ, 0xc0, !PT ;  // t")
L("    SHF.L.U32 R89, R88, 0x2, RZ ;            // 4t")
L()
L("    // desc = d_desc + pair*48 ; fields: a, as, b(codes), bs, c, m_rows")
L("    LDC.64 R2, c[0x0][0x380] ;               // d_desc")
L("    IMAD R0, R92, 0x30, RZ ;")
L("    IMAD.WIDE.U32 R2, R0, 0x1, R2 ;")
L("    LDG.E.128 R4, desc[UR4][R2.64] ;         // a_lo,a_hi,as_lo,as_hi")
L("    LDG.E.128 R8, desc[UR4][R2.64+0x10] ;    // b_lo,b_hi,bs_lo,bs_hi")
L("    LDG.E.128 R12, desc[UR4][R2.64+0x20] ;   // c_lo,c_hi,m,pad")
L("    MOV R64, R4 ; MOV R65, R5 ;              // d_a")
L("    MOV R66, R6 ; MOV R67, R7 ;              // d_as")
L("    MOV R68, R8 ; MOV R69, R9 ;              // d_b (3-bit plane)")
L("    MOV R74, R10 ; MOV R75, R11 ;            // d_bs (scale plane)")
L("    MOV R76, R12 ; MOV R77, R13 ;            // d_c")
L("    MOV R79, R14 ;                           // m_rows")
L("    // pad pair (m_rows==0, moe_align filler): leave before any plane I/O")
L("    ISETP.EQ.AND P4, PT, R79, RZ, PT ;")
L("    @P4 EXIT ;")
L("    LDC R78, c[0x0][0x390] ;                 // ldc")
L()
L("    // P2: g < m_rows (rows 0..7); P3: t==0 && P2")
L("    ISETP.LT.AND P2, PT, R87, R79, PT ;")
L("    ISETP.EQ.AND P3, PT, R88, RZ, P2 ;")
if MC == 4:
    L("    IADD3 R0, PT, PT, R79, -0x8, RZ ;")
    L("    ISETP.LT.AND P5, PT, R87, R0, PT ;")  # P5: g+8 < m_rows
L()
L("    // B plane ptr: (ctaid.x*(K/64) + wid*(KSLICE/64)) blocks of 384B")
L("    // (256B low + 128B hi per (nb,k64)), + lane*8 into the low region")
L("    LDC R83, c[0x0][0x38c] ;                 // n_k64 = K/64")
L("    IMAD R0, R81, R83, RZ ;                  // nb * n_k64")
L(f"    IMAD R0, R85, {hex(KSLICE // 64)}, R0 ;  // + wid slice base (k64 units)")
L("    IMAD R0, R0, 0x180, RZ ;                 // *384B per (nb,k64) block")
L("    IMAD.WIDE.U32 R8, R0, 0x1, R68 ;")
L("    SHF.L.U32 R1, R86, 0x3, RZ ;             // lane*8")
L("    IMAD.WIDE.U32 R8, R1, 0x1, R8 ;          // -> R8: lane's low-plane ptr")
L("    // hi-plane ptr: block base + 0x100 + lane*4")
L("    IADD3 R0, PT, PT, R0, 0x100, RZ ;")
L("    IMAD.WIDE.U32 R10, R0, 0x1, R68 ;")
L("    SHF.L.U32 R1, R86, 0x2, RZ ;             // lane*4")
L("    IMAD.WIDE.U32 R10, R1, 0x1, R10 ;        // -> R10: lane's hi-plane ptr")
L()
L("    // Bs plane ptr: ((nb*(K/32) + wid*(KSLICE/32))*16 + g  [16 row")
L("    // bytes per k32; lane reads row g (tile0) and row 8+g (tile1)]")
L("    SHF.R.U32.HI R0, RZ, 0x5, R82 ;          // K/32")
L("    IMAD R1, R81, R0, RZ ;")
L(f"    IMAD R1, R85, {hex(KSLICE // 32)}, R1 ;")
L("    SHF.L.U32 R1, R1, 0x4, RZ ;              // *16")
L("    IADD3 R1, PT, PT, R1, R87, RZ ;          // + g")
L("    IMAD.WIDE.U32 R74, R1, 0x1, R74 ;        // -> R74: lane's sbyte ptr")
L()
L("    // A row ptr (row g, direct fp8) + As ptr (f32 [M, K/128])")
if AFRAG:
    L("    // A-frag ptr: base + wid*(16*KSLICE) + lane*32 ; LDG.128 per k32")
    L(f"    IMAD R0, R85, {hex(16 * KSLICE)}, RZ ;   // wid * 16*KSLICE bytes")
    L("    IMAD R0, R86, 0x20, R0 ;                 // + lane*32 (lane's frag)")
    L("    IMAD.WIDE.U32 R64, R0, 0x1, R64 ;        // -> R64: lane A-frag ptr")
else:
    L("    IMAD.WIDE.U32 R64, R87, R82, R64 ;       // + g*K")
    L("    IMAD.WIDE.U32 R64, R89, 0x1, R64 ;       // + 4t")
    L(f"    IMAD R0, R85, {hex(KSLICE)}, RZ ;")
    L("    IMAD.WIDE.U32 R64, R0, 0x1, R64 ;        // + wid K-slice")
L("    SHF.L.U32 R0, R84, 0x2, RZ ;             // As row stride = n_kb128*4")
L("    IMAD.WIDE.U32 R66, R87, R0, R66 ;        // + g*stride")
L(f"    IMAD.WIDE.U32 R66, R85, {hex((KSLICE // 128) * 4)}, R66 ;")
L()
L("    // constants: pad A words zero, LUT pool, neutral sfa, kb accs zero")
L("    MOV R28, 0x7f7f7f7f ;                    // sfa neutral")
for r in (5, 7, 21, 23, 4, 6, 20, 22, 30, 31, 40, 41, 42, 43, 44, 45, 46, 47):
    L(f"    MOV R{r}, RZ ;")
_LUT_LO = os.environ.get("MOEW3_LUT_LO", "")
_LUT_HI = os.environ.get("MOEW3_LUT_HI", "")
if _LUT_LO or _LUT_HI:
    # e43 anchor: 8 e4m3 LUT bytes little-endian in the pool
    # words (LUT[0] = R27 byte 0 ... LUT[7] = R13 byte 3). Default emission
    # below stays BYTE-IDENTICAL when the env overrides are unset.
    assert _LUT_LO and _LUT_HI, "set both MOEW3_LUT_LO and MOEW3_LUT_HI"
    L(f"    MOV R27, {_LUT_LO} ;                    // LUT lo pool (env override)")
    L(f"    MOV R13, {_LUT_HI} ;                    // LUT hi pool (env override)")
else:
    L("    MOV R27, 0xb0bcc4cc ;                    // LUT lo: -6,-3,-1.5,-0.5 e4m3")
    L("    MOV R13, 0x4c443c30 ;                    // LUT hi:  .5,1.5,  3,  6 e4m3")
for r in (48, 49, 50, 51, 52, 53, 54, 55):
    L(f"    MOV R{r}, RZ ;")
L()


def emit_k64(j):
    """One k64: load 8B low + 4B hi codes + 4 sbytes + A bytes; decode; QMMA."""
    plane_off = 0x180 * j           # 384B per (nb,k64) block
    aoff = 0x40 * j
    soff = 0x20 * j                 # 2 k32 x 16 row bytes per k64
    kb = j // 2
    L(f"    // ---- k64 {j} (kb128 {kb}) ----")
    if j % 2 == 0:
        L(f"    @P2 LDG.E R30, desc[UR4][R66.64+{hex(kb * 4)}] ;  // As[g,kb] f32")
        if MC == 4:
            as_ck = 8 * (K // 128) * 4  # +8 rows of As (stride n_kb128*4)
            L(f"    @P5 LDG.E R31, desc[UR4][R66.64+{hex(kb * 4 + as_ck)}] ;  // As[g+8,kb]")
    # low plane: R24 = bytes [t0a_lo, t0a_hi, t0b_lo, t0b_hi], R25 = tile1
    L(f"    LDG.E.64 R24, desc[UR4][R8.64+{hex(plane_off)}] ;     // low codes 8B")
    L(f"    LDG.E R12, desc[UR4][R10.64+{hex(plane_off)}] ;       // hi bits 4B")
    L(f"    LDG.E.U8 R26, desc[UR4][R74.64+{hex(soff)}] ;         // S[g, k32a]")
    L(f"    LDG.E.U8 R29, desc[UR4][R74.64+{hex(soff + 0x8)}] ;   // S[8+g, k32a]")
    L(f"    LDG.E.U8 R56, desc[UR4][R74.64+{hex(soff + 0x10)}] ;  // S[g, k32b]")
    L(f"    LDG.E.U8 R57, desc[UR4][R74.64+{hex(soff + 0x18)}] ;  // S[8+g, k32b]")
    if AFRAG:
        # fragment-major A: the lane's whole m16k32 A-fragment (4 words = rows
        # g/g+8 x 2 K-quads) is contiguous -> 1 LDG.128 per k32 (no per-row pred;
        # pad rows are zero in the buffer and masked at store).
        L(f"    LDG.E.128 R4, desc[UR4][R64.64+{hex(0x400 * j)}] ;        // A-frag k32a rows0-15 -> R4-7")
        L(f"    LDG.E.128 R20, desc[UR4][R64.64+{hex(0x400 * j + 0x10)}] ;  // A-frag k32b rows0-15 -> R20-23")
    else:
        L(f"    @P2 LDG.E R4, desc[UR4][R64.64+{hex(aoff)}] ;         // A w0 lo (row g)")
        L(f"    @P2 LDG.E R6, desc[UR4][R64.64+{hex(aoff + 0x10)}] ;  // A w2 (row g)")
        L(f"    @P2 LDG.E R20, desc[UR4][R64.64+{hex(aoff + 0x20)}] ;")
        L(f"    @P2 LDG.E R22, desc[UR4][R64.64+{hex(aoff + 0x30)}] ;")
        if MC == 4:
            # a1/a3 fragment slots = rows g+8 -> the c2/c3 QMMA quadrants. Load the
            # upper-half tokens (offset +8 rows = +8*K bytes) into R5/R7/R21/R23.
            a_ck = 8 * K
            L(f"    @P5 LDG.E R5, desc[UR4][R64.64+{hex(aoff + a_ck)}] ;          // a1 k32a row g+8")
            L(f"    @P5 LDG.E R7, desc[UR4][R64.64+{hex(aoff + 0x10 + a_ck)}] ;   // a3 k32a row g+8")
            L(f"    @P5 LDG.E R21, desc[UR4][R64.64+{hex(aoff + 0x20 + a_ck)}] ;  // a1 k32b row g+8")
            L(f"    @P5 LDG.E R23, desc[UR4][R64.64+{hex(aoff + 0x30 + a_ck)}] ;  // a3 k32b row g+8")
    L("    // spread 2-bit low codes to nibble selectors, OR hi bit at nibble")
    L("    // bit2, PRMT over the 8-entry pool {R27,R13}")
    # byte b of R24/R25 -> selector word; hi nibble gidx of R12 -> bit2s.
    # decode into B regs: k32a tile0 pair (R32,R33), k32b (R34,R35),
    # tile1 from R25 -> (R36,R37),(R38,R39)
    for gidx, ((src, bit), dst) in enumerate((
        (("R24", 0), 32), (("R24", 8), 33), (("R24", 16), 34), (("R24", 24), 35),
        (("R25", 0), 36), (("R25", 8), 37), (("R25", 16), 38), (("R25", 24), 39),
    )):
        # low 2 bits: n = b&3 | (b&0xC)<<2 | (b&0x30)<<4 | (b&0xC0)<<6
        L(f"    SHF.R.U32.HI R0, RZ, {hex(bit)}, {src} ;" if bit else
          f"    MOV R0, {src} ;")
        L("    LOP3.LUT R1, R0, 0x03, RZ, 0xc0, !PT ;")
        L("    LOP3.LUT R2, R0, 0x0c, RZ, 0xc0, !PT ;")
        L("    LOP3.LUT R3, R0, 0x30, RZ, 0xc0, !PT ;")
        L("    LOP3.LUT R0, R0, 0xc0, RZ, 0xc0, !PT ;")
        L("    IMAD R1, R2, 0x4, R1 ;                   // |= (b&0xC)<<2")
        L("    IMAD R1, R3, 0x10, R1 ;")
        L("    IMAD R1, R0, 0x40, R1 ;")
        # hi bit: x = (hi >> 4*gidx) & 0xF ; selector |= bit k of x -> bit 4k+2
        L(f"    SHF.R.U32.HI R2, RZ, {hex(4 * gidx)}, R12 ;" if gidx else
          "    MOV R2, R12 ;")
        L("    LOP3.LUT R3, R2, 0x1, RZ, 0xc0, !PT ;")
        L("    IMAD R1, R3, 0x4, R1 ;                   // hi0 -> sel bit2")
        L("    LOP3.LUT R3, R2, 0x2, RZ, 0xc0, !PT ;")
        L("    IMAD R1, R3, 0x20, R1 ;                  // hi1 -> sel bit6")
        L("    LOP3.LUT R3, R2, 0x4, RZ, 0xc0, !PT ;")
        L("    IMAD R1, R3, 0x100, R1 ;                 // hi2 -> sel bit10")
        L("    LOP3.LUT R3, R2, 0x8, RZ, 0xc0, !PT ;")
        L("    IMAD R1, R3, 0x800, R1 ;                 // hi3 -> sel bit14")
        L(f"    PRMT R{dst}, R27, R1, R13 ;              // 4x e4m3 bytes (8-LUT)")
    L("    // QMMA per k32; sfb = the lane's COLUMN row scale (tile-exact)")
    L("    QMMA.SF.16832.F32.E4M3.E4M3.E8 R40, R4.ROW, R32.COL, R40, R28, R26, UR6 ;")
    L("    QMMA.SF.16832.F32.E4M3.E4M3.E8 R44, R4.ROW, R36.COL, R44, R28, R29, UR6 ;")
    L("    QMMA.SF.16832.F32.E4M3.E4M3.E8 R40, R20.ROW, R34.COL, R40, R28, R56, UR6 ;")
    L("    QMMA.SF.16832.F32.E4M3.E4M3.E8 R44, R20.ROW, R38.COL, R44, R28, R57, UR6 ;")
    if j % 2 == 1:
        L(f"    // fold kb128 {kb}: master += acc_kb * As (B scale already in SF)")
        L("    FFMA R48, R40, R30, R48 ;")
        L("    FFMA R49, R41, R30, R49 ;")
        L("    FFMA R52, R44, R30, R52 ;")
        L("    FFMA R53, R45, R30, R53 ;")
        L("    MOV R40, RZ ; MOV R41, RZ ;")
        L("    MOV R44, RZ ; MOV R45, RZ ;")
        if MC == 4:
            # c2/c3 (rows g+8) scaled by As[g+8] (R31) -> masters R50/51 (t0),
            # R54/55 (t1); reset the c2/c3 acc slots for the next kb128.
            L("    FFMA R50, R42, R31, R50 ;")
            L("    FFMA R51, R43, R31, R51 ;")
            L("    FFMA R54, R46, R31, R54 ;")
            L("    FFMA R55, R47, R31, R55 ;")
            L("    MOV R42, RZ ; MOV R43, RZ ;")
            L("    MOV R46, RZ ; MOV R47, RZ ;")


n_k64 = KSLICE // 64
L(f"    // ---- K march: {n_k64} x k64 ----")
for j in range(n_k64):
    emit_k64(j)
L()
L("    // OCCUPANCY: recompute the IDs the epilogue needs (tid/wid/lane/ctaid.x/")
L("    // ldc) HERE instead of carrying them from the prologue (W2 lineage).")
L("    S2R R80, SR_TID.X ;")
L("    SHF.R.U32.HI R85, RZ, 0x5, R80 ;         // wid")
L("    LOP3.LUT R86, R80, 0x1f, RZ, 0xc0, !PT ; // lane")
L("    S2R R81, SR_CTAID.X ;                     // n-block")
L("    LDC R78, c[0x0][0x390] ;                  // ldc")
L("    // reload d_c + m_rows from desc (free their across-loop live intervals)")
L("    S2R R92, SR_CTAID.Y ;")
L("    LDC.64 R2, c[0x0][0x380] ;                // d_desc")
L("    IMAD R0, R92, 0x30, RZ ;")
L("    IMAD.WIDE.U32 R2, R0, 0x1, R2 ;           // desc ptr")
L("    LDG.E.64 R76, desc[UR4][R2.64+0x20] ;     // d_c (c_lo, c_hi)")
L("    LDG.E R79, desc[UR4][R2.64+0x28] ;        // m_rows")
L("    // ---- epilogue: smem split-K reduce + bf16 store (skinny lineage) ----")
L("    IMAD R0, R85, 0x400, RZ ;")
L("    SHF.L.U32 R1, R86, 0x4, RZ ;")
L("    IADD3 R0, PT, PT, R0, R1, RZ ;")
# slots 2,3 of each ACC are the c2/c3 (row g+8) outputs. MC=1 doesn't fold
# them -> store RZ. MC=4 folds them into R50/51/54/55 (rows 8..15).
def _acc_slot(base, i):
    return f"R{base + i}" if (i < 2 or MC == 4) else "RZ"
for i in range(4):
    L(f"    STS [R0+{hex(i * 4)}], {_acc_slot(ACC0, i)} ;")
for i in range(4):
    L(f"    STS [R0+{hex(0x200 + i * 4)}], {_acc_slot(ACC1, i)} ;")
L("    BAR.SYNC.DEFER_BLOCKING 0x0 ;")
L()


def emit_reduce_store(slot_base):
    sb = f"+{hex(slot_base)}" if slot_base else ""
    L(f"    // slot = tid{sb}")
    if slot_base:
        L(f"    IADD3 R19, PT, PT, R80, {hex(slot_base)}, RZ ;")
    else:
        L("    MOV R19, R80 ;")
    L("    LOP3.LUT R2, R19, 0x7f, RZ, 0xc0, !PT ;")
    L("    SHF.R.U32.HI R3, RZ, 0x7, R19 ;")
    L("    IMAD R4, R3, 0x200, RZ ;")
    L("    IMAD R4, R2, 0x4, R4 ;")
    L("    LDS R30, [R4] ;")
    for wid in range(1, NWARP):
        L(f"    IADD3 R5, PT, PT, R4, {hex(wid * 0x400)}, RZ ;")
        L("    LDS R21, [R5] ;")
        L("    FADD R30, R30, R21 ;")
    L("    SHF.R.U32.HI R20, RZ, 0x2, R2 ;")
    L("    LOP3.LUT R21, R2, 0x3, RZ, 0xc0, !PT ;")
    L("    SHF.R.U32.HI R22, RZ, 0x2, R20 ;")
    L("    SHF.R.U32.HI R23, RZ, 0x1, R21 ;")
    L("    IMAD R22, R23, 0x8, R22 ;")
    L("    LOP3.LUT R24, R20, 0x3, RZ, 0xc0, !PT ;")
    L("    LOP3.LUT R25, R21, 0x1, RZ, 0xc0, !PT ;")
    L("    IMAD R24, R24, 0x2, R25 ;")
    L("    SHF.L.U32 R26, R81, 0x4, RZ ;")
    L("    IMAD R26, R3, 0x8, R26 ;")
    L("    IADD3 R26, PT, PT, R26, R24, RZ ;")
    L("    SHFL.DOWN PT, R31, R30, 0x1, 0x1f ;")
    L("    F2FP.BF16.F32.PACK_AB R31, R31, R30 ;")
    L("    ISETP.LT.AND P1, PT, R22, R79, PT ;")
    L("    ISETP.EQ.AND P1, PT, R25, RZ, P1 ;")
    if NTHR > 256:
        L("    ISETP.LT.U32.AND P1, PT, R19, 0x100, P1 ;")
    L("    IMAD R14, R22, R78, RZ ;")
    L("    IMAD R14, R26, 0x2, R14 ;")
    L("    MOV R15, RZ ;")
    L("    IADD.64 R16, R14, R76 ;")
    L("    @P1 STG.E desc[UR4][R16.64], R31 ;")


for base in range(0, 256, min(NTHR, 256)):
    emit_reduce_store(base)
L("    EXIT ;")

# OCCUPANCY renumber (W2 MC=1/MC=4 remap, verbatim): regcount = (max_reg+32)&~31 ->
# max_reg<=63 gives regcount 64 = 4 CTA/SM. W3 adds R10/R11 (hi ptr, loop-live),
# R12 (hi word, k64-local) and R13 (LUT-hi pool) -- all already <=R61 and all
# OUTSIDE both the remap targets and the reduce scratch set {R2-5,14-26,30,31}
# (R10-13 only live in-loop; reduce runs after). MC=4's extra loop-live regs
# (R31, R50/51/54/55) and extra A loads (R5/7/21/23) are NOT remap targets and
# the MC=4 loop has the SAME free set as MC=1 -> the MC=1 <=R61 renumber applies
# verbatim (per gen_moe_w2.py), giving regcount 64 = 4 CTA/SM. NB: R62/R63 are
# ILLEGAL as MOV-dest / LDG-addr-base on SM120 -> never target them with a pointer.
_remap = {
    64: 58, 65: 59, 66: 60, 67: 61,                    # A, As (loop-live)
    74: 16, 75: 17,                                    # Bs (loop-live)
    68: 32, 69: 33,                                    # d_b base (prologue)
    80: 34, 81: 35, 82: 36, 83: 37, 84: 38, 85: 39,    # tid,ctaid.x,K,nk64,nkb128,wid
    86: 44, 87: 45, 88: 46, 89: 47, 92: 18,            # lane,g,t,4t,ctaid.y
    76: 42, 77: 43, 78: 41, 79: 40,                    # d_c, ldc, m_rows
}
_maxreg = 61
import re as _re


def _occ(s):
    if ".reg R0-R95" in s:
        return s.replace("R0-R95", f"R0-R{_maxreg}")
    for _a in sorted(_remap, reverse=True):   # desc order: extra safety
        s = _re.sub(rf"\bR{_a}\b", f"R{_remap[_a]}", s)
    return s


OUT = [_occ(s) for s in OUT]

path = sys.argv[1] if len(sys.argv) > 1 else "sass/moe_w3_mm.sass"
open(path, "w").write("\n".join(OUT) + "\n")
print(f"wrote {path} ({len(OUT)} lines, K={K}, NWARP={NWARP}, MC={MC}, AFRAG={AFRAG})")
